/* eslint-disable */
export const countries = {
  AFG: { name: 'Afghanistan'  , gridy: 1, gridx: 9 , cluster: 1 },
  AGO: { name: 'Angola'       , gridy: 7, gridx: 5 , cluster: 4 },
  BGD: { name: 'Bangladesh'   , gridy: 3, gridx: 11, cluster: 1 },
  BFA: { name: 'Burkina Faso' , gridy: 4, gridx: 3 , cluster: 2 },
  CMR: { name: 'Cameroon'     , gridy: 5, gridx: 5 , cluster: 3 },
  TCD: { name: 'Chad'         , gridy: 3, gridx: 5 , cluster: 2 },
  CIV: { name: 'Côte d’Ivoire', gridy: 5, gridx: 2 , cluster: 3 },
  COD: { name: 'DR Congo'     , gridy: 6, gridx: 6 , cluster: 1 },
  EGY: { name: 'Egypt'        , gridy: 2, gridx: 6 , cluster: 3 },
  ETH: { name: 'Ethiopia'     , gridy: 4, gridx: 7 , cluster: 1 },
  GHA: { name: 'Ghana'        , gridy: 5, gridx: 3 , cluster: 3 },
  GTM: { name: 'Guatemala'    , gridy: 3, gridx: 1 , cluster: 1 },
  IND: { name: 'India'        , gridy: 2, gridx: 10, cluster: 1 },
  IDN: { name: 'Indonesia'    , gridy: 5, gridx: 12, cluster: 2 },
  IRQ: { name: 'Iraq'         , gridy: 1, gridx: 7 , cluster: 3 },
  KEN: { name: 'Kenya'        , gridy: 5, gridx: 8 , cluster: 2 },
  MDG: { name: 'Madagascar'   , gridy: 7, gridx: 9 , cluster: 1 },
  MWI: { name: 'Malawi'       , gridy: 7, gridx: 7 , cluster: 1 },
  MLI: { name: 'Mali'         , gridy: 3, gridx: 3 , cluster: 2 },
  MOZ: { name: 'Mozambique'   , gridy: 7, gridx: 8 , cluster: 1 },
  MMR: { name: 'Myanmar'      , gridy: 3, gridx: 12, cluster: 2 },
  NPL: { name: 'Nepal'        , gridy: 2, gridx: 11, cluster: 1 },
  NER: { name: 'Niger'        , gridy: 3, gridx: 4 , cluster: 1 },
  NGA: { name: 'Nigeria'      , gridy: 4, gridx: 4 , cluster: 2 },
  PAK: { name: 'Pakistan'     , gridy: 1, gridx: 10, cluster: 2 },
  PHL: { name: 'Philippines'  , gridy: 4, gridx: 13, cluster: 3 },
  RWA: { name: 'Rwanda'       , gridy: 6, gridx: 7 , cluster: 1 },
  ZAF: { name: 'South Africa' , gridy: 8, gridx: 7 , cluster: 3 },
  SDN: { name: 'Sudan'        , gridy: 3, gridx: 6 , cluster: 2 },
  TZA: { name: 'Tanzania'     , gridy: 6, gridx: 8 , cluster: 2 },
  UGA: { name: 'Uganda'       , gridy: 5, gridx: 7 , cluster: 2 },
  VNM: { name: 'Vietnam'      , gridy: 3, gridx: 13, cluster: 5 },
  YEM: { name: 'Yemen'        , gridy: 3, gridx: 8 , cluster: 1 },
  ZMB: { name: 'Zambia'       , gridy: 7, gridx: 6 , cluster: 1 }
};
/* eslint-enable */

export const varLookup = {
  'Children stunted (World Bank)': 0,
  'Adults with HIV': 5,
  'HIV prevalence among young people aged 15-24': 6,
  'HIV prevalence among young men age 15-24': 7,
  'HIV prevalence among young women age 15-24': 8,
  'Heard of ART': 9,
  'Heard of drug to prevent transmission to baby': 10,
  'Mean weight for age of children': 11,
  'Underweight children': 12,
  'Children severely underweight': 13,
  'Children stunted': 14,
  'Children severely stunted': 15,
  'Children wasted': 16,
  'Children severely wasted': 17,
  'Children overweight for height': 18,
  'Children overweight for age': 19,
  'Mean weight for height': 20,
  'Age at first marriage, women': 21,
  'Age at first birth': 22,
  'Contraception use': 23,
  'Total fertility rate': 24,
  'Children per woman': 25,
  'Surviving children': 26,
  'Teen fertility rate': 27,
  'Crude birth rate': 28,
  'Completed fertility': 29,
  'Births attended by skilled health staff': 30,
  'Tetanus injections before birth': 31,
  'Tetanus protection at birth': 32,
  'DPT3 immunized': 33,
  'Malaria according to RDT\r': 34,
  'Malaria according to microscopy': 35,
  'Children under 5 with diarrhea': 36,
  'Cough or fast breathing': 37,
  'Child mortality': 38,
  'Maternal mortality rate': 39,
  'Female deaths that are maternal': 40,
  'Maternal mortality ratio': 41,
  'Under-five mortality': 42,
  'Neonatal mortality rate': 43,
  'Infant mortality rate': 44,
  'Smoking men': 45,
  'Smoking women': 46,
  'Drinks alcohol': 47,
  'Body Mass Index (BMI), women': 48,
  'Women with height below 145 cm': 49,
  'Unclean cooking fuel': 50,
  'Electricity in household': 51,
  'Automobile in household': 52,
  'Cell phone in household': 53,
  'Phone in household': 54,
  'Internet in household': 55,
  'Computer in household': 56,
  'Improved sanitation, overall access': 57,
  'Improved sanitation, rural access': 58,
  'Improved sanitation, urban access': 59,
  'Piped water, overall access': 60,
  'Piped water, rural access': 61,
  'Piped water, urban access': 62,
  'Literacy rate, adults age 15+': 63,
  'Literacy rate, females age 15+': 64,
  'Literacy rate, males age 15+': 65,
  'Literacy rate, youth age 15-24': 66,
  'Literacy rate, females age 15-24': 67,
  'Literacy rate, males age 15-24': 68,
  'Ratio of young literate females to males': 69,
  'Mean years of school, persons age 25-34': 70,
  'Mean years of school, men age 25-34': 71,
  'Mean years of school, women age 25-34': 72,
  'Mean years of school, men age 25+': 73,
  'Mean years of school, women age 25+': 74,
  'Mean years of school, women age 15-44': 75,
  'Primary school complete, age 15-24': 76,
  'Primary school complete, males age 15-24': 77,
  'Primary school complete, females age 15-24': 78,
  'Primary school complete, age 15+': 79,
  'Primary school complete, males age 15+': 80,
  'Primary school complete, females age 15+': 81,
  'Primary school complete, age 15-64': 82,
  'Primary school complete, males age 15-64': 83,
  'Primary school complete, females age 15-64': 84,
  'Ratio of girls to boys attending school': 85,
  'Chidren out of school, total': 86,
  'Chidren out of school, female': 87,
  'Chidren out of school, male': 88,
  'Employment rate, age 15+': 89,
  'Labor force participation rate, age 15+': 90,
  'Unemployment rate, age 15+': 91,
  'Employment rate, age 15-24': 92,
  'Unemployment rate, age 15-24': 93,
  'Labor force participation rate, age 15-64': 94,
  'Labor force participation rate, age 25-54': 95,
  'Unemployment rate, age 25-54': 96,
  'Unemployment rate, age 55+': 97,
  'Labor force participation rate, age 65+': 98,
  'Female employment rate, age 15+': 99,
  'Female labor force participation rate, age 15+': 100,
  'Female unemployment rate, age 15+': 101,
  'Female employment rate, age 15-24': 102,
  'Female unemployment rate, age 15-24': 103,
  'Female labor force participation rate, age 15-64': 104,
  'Female labor force participation rate, age 25-54': 105,
  'Female unemployment rate, age 25-54': 106,
  'Female unemployment rate, age 55+': 107,
  'Female labor force participation rate, age 65+': 108,
  'Male employment rate, age 15+': 109,
  'Male labor force participation rate, age 15+': 110,
  'Male unemployment rate, age 15+': 111,
  'Male employment rate, age 15-24': 112,
  'Male unemployment rate, age 15-24': 113,
  'Male labor force participation rate, age 15-64': 114,
  'Male labor force participation rate, age 25-54': 115,
  'Male unemployment rate, age 25-54': 116,
  'Male unemployment rate, age 55+': 117,
  'Male labor force participation rate, age 65+': 118,
  'Agriculture workers, percent of labor force': 119,
  'Family workers, percent of labor force': 120,
  'Industry workers, percent of labor force': 121,
  'Salaried workers, percent of labor force': 122,
  'Self-employed, percent of labor force': 123,
  'Service workers, percent of labor force': 124,
  'Female agriculture workers, percent of female labor force': 125,
  'Female family workers, percent of female labor force': 126,
  'Female industry workers, percent of female labor force': 127,
  'Female salaried workers, percent of female labor force': 128,
  'Female self-employed, percent of female labor force': 129,
  'Female service workers, percent of female labor force': 130,
  'Male agriculture workers, percent of male labor force': 131,
  'Male family workers, percent of male labor force': 132,
  'Male industry workers, percent of male labor force': 133,
  'Male salaried workers, percent of male labor force': 134,
  'Male self-employed, percent of male labor force': 135,
  'Male service workers, percent of male labor force': 136,
  'Hours worked per week': 137,
  'Dependency ratio': 138,
  'Sex ratio': 139,
  'Sex ratio, 0-14 years': 140,
  'Sex ratio, 15-24 years': 141,
  'Sex ratio, 15-49 years': 142,
  'Sex ratio, 50+ years': 143,
  'Urban population': 144,
  'Urban population, percent of total': 145,
  'Total population': 146,
  'Female population': 147,
  'Male population': 148,
  'Population age 0-4 years, total': 149,
  'Population age 0-4 years, percent of total': 150,
  'Population age 0-4 years, percent of female population': 151,
  'Population age 0-4 years, percent of male population': 152,
  'Population age 5-9 years, total': 153,
  'Population age 5-9 years, percent of total': 154,
  'Population age 5-9 years, percent of female population': 155,
  'Population age 5-9 years, percent of male population': 156,
  'Population age 10-14 years, total': 157,
  'Population age 10-14 years, percent of total': 158,
  'Population age 10-14 years, percent of female population': 159,
  'Population age 10-14 years, percent of male population': 160,
  'Population age 15-19 years, total': 161,
  'Population age 15-19 years, percent of total': 162,
  'Population age 15-19 years, percent of female population': 163,
  'Population age 15-19 years, percent of male population': 164,
  'Population age 20-39 years, total': 165,
  'Population age 20-39 years, percent of total': 166,
  'Population age 20-39 years, percent of female population': 167,
  'Population age 20-39 years, percent of male population': 168,
  'Population age 40-59 years, total': 169,
  'Population age 40-59 years, percent of total': 170,
  'Population age 40-59 years, percent of female population': 171,
  'Population age 40-59 years, percent of male population': 172,
  'Population age 60+ years, total': 173,
  'Population age 60+ years, percent of total': 174,
  'Population age 60+ years, percent of female population': 175,
  'Population age 60+ years, percent of male population': 176,
  'Median age': 177
};
